### ISSUE TITLE
Possible Windows Port?

### ISSUE THREAD

**Issue by ndo360** [reddec/tinc-boot#1]
Greetings!

I am presently working on creating a Tinc network and found your project and thought it could be an amazing fit. The issue is that there are nodes that operate on windows.

I didn't see the page mentioning any setup for other operating systems outside Linux, which leads me to presume there isn't a way to apply this project to nodes running off of windows.

Could it be possible down the line to port to windows, or not as of right now?

Cheers!

**Comment by reddec** [comment]
Good day! 

Yes, the project primarily focus on POSIX based operation systems: Linux, FreeBSD, MacOSx and so on. This is a main platforms are mostly interested for me right now. In addition and with all respect to MS I am heavily disappointed in MS strategy of Windows, so it is personal :smiley: (kinda ironic to write this on Microsoft-owned Github)

However, I will be happy to consult any person who will be brave enough to port the project to the NT platform and I will include such patch(es) if needed. 

With regards, reddec

**Comment by ndo360** [comment]
Ah I figured as much.

I am hoping to use Tinc to create a network for people to play old games' multiplayer features once again. However said games are on Windows, and the reason I was attracted to your project was the ease of adding new nodes and the sort.

I would hope that this project somehow gets ported to Windows somehow, I would love to use it. 

P.S. I will say the older games is 'Splinter Cell: Chaos Theory' & ' Splinter Cell: Double Agent.'

**Comment by reddec** [comment]
Let's agree if no one else will make a PR and the issue will get at least 10 likes (means it is valuable feature), I will force myself to do it))

Thanks for the issue and that you are interested in the project!

**Comment by ndo360** [comment]
Alright you have a deal. I'll ask some people in the community and we'll see if we can get this post the 10 likes it needs. 

Cheers!

**Comment by reddec** [comment]
OK, deal is deal :smile:  I will do it

**Comment by ndo360** [comment]
Thanks! It means a lot. 

Once ported to Windows, and a guide made, hopefully the community will enjoy playing online in a decentralized environment... without the risk of a single point of failure. 

Cheers Again!

**Comment by reddec** [comment]
Done

See https://github.com/reddec/tinc-boot#windows

**Comment by ndo360** [comment]
Greetings once more!

I see the link but I am confused on how to obtain the EXE file... Am I missing the location as to where you posted it?

**Comment by ndo360** [comment]
I managed to compile it, apologies for the bother!

**Comment by reddec** [comment]
Binary will be uploaded after new release
