### ISSUE TITLE
Error when creating bootnode.

### ISSUE THREAD

**Issue by ndo360** [reddec/tinc-boot#2]
Greetings!

I was following the guide, and everything was looking positive until I tried to convert the node into a boot node. This is the error I got.
![image](https://user-images.githubusercontent.com/13690264/72933791-6cb8db00-3d30-11ea-8968-a749128d17fd.png)

I am using a compiled windows version of tinc-boot to do this. Am I doing something wrong?

**Comment by reddec** [comment]
Windows version is not supporting to be a bootnode =(

**Comment by ndo360** [comment]
Will this issue hopefully be resolved?

**Comment by reddec** [comment]
Will see. Not sure that `--service` flag will be supportrd

**Comment by reddec** [comment]
[tinc-boot_windows_amd64.tar.gz](https://github.com/reddec/tinc-boot/files/4101461/tinc-boot_windows_amd64.tar.gz)
Try latest version (`--service` not supported)
