### ISSUE TITLE
Minor Issues

### ISSUE THREAD

**Issue by ndo360** [reddec/tinc-boot#3]
Greetings!

I encountered another issue on the windows port. It seems that whenever you make a slight change to the virtual adapter, the webpage interface rejects the connection.
(In my case I just wanted to change the interface metric...)

Also is there a debug mode available? Reason I ask is I am not entirely sure if the nodes are fully connecting or not.

Cheers!

**Comment by reddec** [comment]
Hi!

First of all: tinc debug is not trivial. Especially on windows. Actually I could recommend you to run `tincd -n dnet -D` on Linux machine, but not sure it's applicable for NT OS.

Second: highly-likely (according to your description) you are trying to change IP settings of adapter that could cause broken bridge between your system and VPN. `tinc-boot` aimed to hide such problems (or better say - help for target users). I may try to help you if you will give me more details of your setup, however, on my tests even Windows machine can connect to other nodes and work as expected

**Comment by ndo360** [comment]
Thanks for the quick response!

I am not touching the IP settings of the adapter in the sense of setting a static ip or anything.

What I am changing is the interface's priority. (Also known as the metric) This allows for broadcasts and the sort to be routed through the interface. (Mainly so that the games being hosted on the network could be visible.)

To access this setting go to the interface --> properties --> IPv4 --> Advanced Settings. Once there you will see the metric option at the bottom, what I tend to do is manually set the metric to one.

For some reason this breaks the web interface for Tinc-boot...

On another side note, when I did connect two different nodes. (Not touching the interface settings, working web interface and the sort) The webpage didn't show or mention the connected node. The connected node got an IP Address and everything, but it cannot ping the standalone public node nor does it appear in the webpage.

If you happen to use Discord I can talk with you over instant messaging and give you a clearer picture.

**Comment by reddec** [comment]
Okay. It sounds like a more deep problem. https://discord.gg/CfMBthk
