### ISSUE TITLE
Support for tinc v1.1 

### ISSUE THREAD

**Issue by manwegit** [reddec/tinc-boot#5]
Hi
I really like the idea of tinc-boot, but would like to get it to work with tinc 1.1pre*

**Comment by reddec** [comment]
Good day!
Thanks for your interest.
There are two complications with tinc 1.1-pre: 

1. it still not released; IMHO unreleased software related to the security should not even be considered to use in a production environment. That is only one reason why I started tinc-boot as a wrapper on top of tinc 1.0.x.
2. it already have 90% of tinc-boot embedded: it has initiations, peer sharing, hosts files dump and so on. And it was made by professionals in a light and straightforward way.

I strictly not recommend you or anyone else use unreleased version of software which main priority is security (tinc 1.1 branch), however if you are ready to accept the risk, I would like you to recommend to read native documentation: it's quite simple. No need to make a wrapper (tinc-boot) on top of it.
