### ISSUE TITLE
'go get' fails

### ISSUE THREAD

**Issue by jvasile** [reddec/tinc-boot#6]
I just now tried to build this using go get, but I received the error below.  I haven't tried to debug it, but I figured I'd let you know.

    $ go get -v github.com/reddec/tinc-boot/cmd/...
    github.com/reddec/tinc-boot/domain/monitor
    # github.com/reddec/tinc-boot/domain/monitor
    /usr/local/src/golang/src/github.com/reddec/tinc-boot/domain/monitor/service.go:58:37: stream.Handler undefined (type *events.wsStreamer has no field or method Handler)
    /usr/local/src/golang/src/github.com/reddec/tinc-boot/domain/monitor/service.go:64:9: stream.Close undefined (type *events.wsStreamer has no field or method Close)

**Comment by reddec** [comment]
Which go version are you using?

**Comment by jvasile** [comment]
My golang is installed from Debian's testing repository and is version 1.14.

**Comment by reddec** [comment]
Seems like is is a local problem - just run on clean VM without problem
