### ISSUE TITLE
customize the subnet

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [reddec/tinc-boot#7]
Hi there,
is there any option to set a specific subnet?
I would like to use 10.0.0.0/16 as a subnet and choose a static ip for each node rather than random
thanks

**Comment by reddec** [comment]
Please check `tinc-boot gen --help` command.

Specifically for your questions:

* Use 10.0.0.0/16: `--prefix 10.0` (16 mask is by default).
* Static IP is same as above: `--prefix 10.0.1.2`

Idea is that the leftover part of IP will be randomly generated. If you defined everything - it will be static.
