### ISSUE TITLE
Tinc network goes down when bootnode is not available

### ISSUE THREAD

**Issue by raghubuilds** [reddec/tinc-boot#8]
Hi, I created Tinc VPN with tinc-boot. The setup consists of 3 VM's, out of which one acts as the bootnode. Running Tinc in switch mode because I need to run Keepalived over Tinc. Everything works fine when bootnode is running, but once it goes down no node can reach each other. How can I solve this single point of failure?
Steps followed:
1. tinc-boot standalone on VM1
2. tinc-boot bootnode <TOKEN> on VM1
3. tinc-boot gen --token <TOKEN> <VM1-PublicAddress>:8655 on other machines.

**Comment by reddec** [comment]
Hi!

It could be two problems:

*Nodes didn't exchange keys*
Case: for some reason, nodes configuration are not exchanged. It means, nodes don't know about each other except bootnode.
Symptoms: no hosts files in dir
Solution: check logs for errors.

*NAT*
Case: all nodes except bootnode have a strict NAT (ie it's impossible to establish P2P connection by "hole-punch").
Symptoms: P2P applications are not working
Solution: keep somewhere node with less strict NAT - tinc will use it as relay.

**Comment by raghubuilds** [comment]
Thank you for your quick response.

Case1: All hosts files present in /etc/tinc/dnet/hosts in every node. Keys are exchanged perfectly. 
Case2: VMs are not behind NAT and have publicly accessible IPs. 

I ran these exact commands
On bootnode:

`sudo tinc-boot gen --standalone --port=39999 --prefix=172.173.1 --mask=24 -a <PUBLIC-IP>`
`sudo tinc-boot bootnode --service --token <TOKEN>`

On other nodes:

`sudo tinc-boot gen --token <TOKEN> <BOOTNODE-PUBLIC-IP>:8655 --port=39999 --prefix=172.173.1 --mask=24 -a <NODE-PUBLIC-IP>`

**Comment by raghubuilds** [comment]
Sorry. It's my mistake. Address field was missing hosts configuration file. Cleaned everything and started fresh, now everything working perfeclty. Thank you for creating tinc-boot, this made our life easier.
